In [2]:
import numpy as np
import time

In [3]:
X=np.random.rand(1000, 1000)


In [13]:
dis1 = np.abs(X[:, np.newaxis, :] - X[np.newaxis, :, :]).sum(axis=2) #using numpy
dis2=np.zeros((X.shape[0],X.shape[0])) # the for loop with linalg norm
for i in range(X.shape[0]):
    for j in range(X.shape[0]):
        dis2[i,j]=np.linalg.norm(X[i]-X[j],1)
dis1

array([[  0.        , 321.35688166, 322.84239091, ..., 325.69283127,
        341.83455113, 334.96651773],
       [321.35688166,   0.        , 329.17729888, ..., 340.12667609,
        329.94354618, 341.57371608],
       [322.84239091, 329.17729888,   0.        , ..., 340.80567774,
        322.69144798, 339.5978518 ],
       ...,
       [325.69283127, 340.12667609, 340.80567774, ...,   0.        ,
        334.91827771, 337.73179274],
       [341.83455113, 329.94354618, 322.69144798, ..., 334.91827771,
          0.        , 336.0562981 ],
       [334.96651773, 341.57371608, 339.5978518 , ..., 337.73179274,
        336.0562981 ,   0.        ]])

In [7]:
time_start = time.time()
dis1 = np.abs(X[:, np.newaxis, :] - X[np.newaxis, :, :]).sum(axis=2)
time_end = time.time() 
time_sum = time_end - time_start 
f = open("numpy_para.txt", "w") 
f.write("time is %f"%time_sum) 
f.close()
time_start = time.time()
dis2=np.zeros((X.shape[0],X.shape[0]))
for i in range(X.shape[0]):
    for j in range(X.shape[0]):
        dis2[i,j]=np.linalg.norm(X[i]-X[j],1)
time_end = time.time() 
time_sum = time_end - time_start 
f=open("for_norm.txt","w")
f.write("time is %f"%time_sum)
f.close()
np.savetxt("dis_m.txt",dis2,fmt='%d')

In [33]:
dis=dis1
from sklearn.neighbors import NearestNeighbors
k=10
time_start = time.time()
indices = np.argsort(dis1, axis=1)[:, 1:k+1]
time_end = time.time() 
time_sum = time_end - time_start
print(time_sum)

time_start = time.time()
nbrs = NearestNeighbors(n_neighbors=k+1, algorithm='auto').fit(dis)
distances, indices2 = nbrs.kneighbors(dis)
time_end = time.time() 
time_sum = time_end - time_start
print(time_sum)

import numpy as np
from scipy.spatial import KDTree
tree = KDTree(X)
time_start = time.time()

distances, indices3 = tree.query(X, k=k+1)
time_end = time.time() 
time_sum = time_end - time_start
print(time_sum)
from sklearn.neighbors import BallTree
tree = BallTree(X, leaf_size=5)
time_start = time.time()

distances, indices4 = tree.query(X, k=k+1)
time_end = time.time() 
time_sum = time_end - time_start
print(time_sum)

indices2[:3],indices[:3],indices3[:3],indices4[:3]

0.04600238800048828
0.03200125694274902
2.331395149230957
0.9355790615081787


(array([[  0, 226, 577, 306, 268, 290,  73, 923, 658, 211, 653],
        [  1, 756, 849, 319,  75, 596, 996, 712, 401, 197, 609],
        [  2, 794,   9, 301, 215, 751, 837, 923, 925, 960, 622]],
       dtype=int64),
 array([[226,  73, 306, 826, 969, 577, 211, 658, 820,  28],
        [756, 996, 849, 939, 319, 712, 986,  75, 518, 197],
        [794, 301, 751, 960, 871, 837, 923, 537,  83, 223]], dtype=int64),
 array([[  0, 226, 826, 306,  68, 290, 211,  73, 461, 607, 577],
        [  1, 939, 319, 849, 996, 756, 494, 197,  49, 712, 873],
        [  2, 301, 794, 751, 810, 960, 871, 622,   9, 933, 923]],
       dtype=int64),
 array([[  0, 226, 826, 306,  68, 290, 211,  73, 461, 607, 577],
        [  1, 939, 319, 849, 996, 756, 494, 197,  49, 712, 873],
        [  2, 301, 794, 751, 810, 960, 871, 622,   9, 933, 923]],
       dtype=int64))